# Site settings
title: Rizwan
general_email: mohdrizwan.shaikh2112@gmail.com
academic_email: mohdrizwan.shaikh@iiitb.ac.in

description: > # this means to ignore newlines until "baseurl:"
  I believe, the hunger to learn should never saturate.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://rizwan-s.github.io/" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: Rizwan-S
linkedin_username: rizwans21
facebook_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
